name: create release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "v${{ github.run_number }}" --notes "$(git log -1 --pretty=%B)"